spring:
  datasource:
    url: jdbc:h2:mem:myDb;INIT=create schema if not exists oauth2
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: oauth2
  redis:
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
server:
  port: 8080