spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.yaml
    enabled: true
  redis:
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
server:
  port: 8080
